### ISSUE TITLE
cannot compile included juce with recent gcc 

### ISSUE THREAD

**Issue by shimpe** [kmatheussen/mammut#8]
e.g.
In member function ‘juce::uint8& juce::PixelARGB::getAlpha()’:
../juce_5_3_2/JuceLibraryCode/modules/juce_graphics/colour/juce_PixelFormats.h:116:77: error: cannot bind packed field ‘((juce::PixelARGB*)this)->juce::PixelARGB::<anonymous>.juce::PixelARGB::<unnamed union>::comps[3]’ to ‘juce::uint8&’ {aka ‘unsigned char&’}
  116 |     forcedinline uint8& getAlpha() noexcept           { return comps [indexA]; }

**Comment by alexarje** [comment]
I get the same error on Ubuntu 24.04. Any workarounds?

**Comment by kmatheussen** [comment]
Try now.

**Comment by alexarje** [comment]
Thanks, it solved that problem, but I got into some more trouble due to missing libraries. In case someone else gets here and wants help, this is what I needed to do to make it work: 

1. Install [libsndfile](https://github.com/libsndfile/libsndfile)
1. Install some dependencies `sudo apt-get install libgl1-mesa-dev libsamplerate0-dev libvorbis-dev`

**Comment by kmatheussen** [comment]
Great to hear, and for the record, missing dependencies by JUCE are more
difficult to fix since the error messages are more cryptic.
It might be a good idea to check that this command succeeds before
compiling JUCE:

pkg-config --cflags alsa freetype2 libcurl x11 xext xinerama
